// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4c-01lLC8mq1gcj0d9apBbWajgG_mJn8',
    appId: '1:214522219716:web:e82f56014c6f1301b64d91',
    messagingSenderId: '214522219716',
    projectId: 'ui-sigma',
    authDomain: 'ui-sigma.firebaseapp.com',
    storageBucket: 'ui-sigma.firebasestorage.app',
    measurementId: 'G-BK4DBJP4PE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXqMFWL3FnoXFn7uhUFdnHpik7L6Hx3iU',
    appId: '1:214522219716:android:dfa2baed5e4699cbb64d91',
    messagingSenderId: '214522219716',
    projectId: 'ui-sigma',
    storageBucket: 'ui-sigma.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu1m2xNnDymnVL0Qix3jv0rP-xoGWkO6s',
    appId: '1:214522219716:ios:6dcb4aad357a7354b64d91',
    messagingSenderId: '214522219716',
    projectId: 'ui-sigma',
    storageBucket: 'ui-sigma.firebasestorage.app',
    iosBundleId: 'com.ui.sigma',
  );
}
