// Mocks generated by Mockito 5.4.6 from annotations
// in sigma_auth/test/clean_architecture_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:multiple_result/multiple_result.dart' as _i5;
import 'package:sigma_auth/sigma_auth.dart' as _i3;
import 'package:sigma_core/sigma_core.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAccountStore_0 extends _i1.SmartFake implements _i2.AccountStore {
  _FakeAccountStore_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeKeyStore_1 extends _i1.SmartFake implements _i2.KeyStore {
  _FakeKeyStore_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSettingsStore_2 extends _i1.SmartFake implements _i2.SettingsStore {
  _FakeSettingsStore_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGeneratedKey_3 extends _i1.SmartFake implements _i2.GeneratedKey {
  _FakeGeneratedKey_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGeneratedSignedKey_4 extends _i1.SmartFake
    implements _i2.GeneratedSignedKey {
  _FakeGeneratedSignedKey_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RegistrationRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegistrationRemoteDataSource extends _i1.Mock
    implements _i3.RegistrationRemoteDataSource {
  MockRegistrationRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.Result<_i3.RegistrationSessionResponse, _i2.Failure>>
  createRegistrationSession(String? phone, {String? clientType = 'android'}) =>
      (super.noSuchMethod(
            Invocation.method(
              #createRegistrationSession,
              [phone],
              {#clientType: clientType},
            ),
            returnValue:
                _i4.Future<
                  _i5.Result<_i3.RegistrationSessionResponse, _i2.Failure>
                >.value(
                  _i6.dummyValue<
                    _i5.Result<_i3.RegistrationSessionResponse, _i2.Failure>
                  >(
                    this,
                    Invocation.method(
                      #createRegistrationSession,
                      [phone],
                      {#clientType: clientType},
                    ),
                  ),
                ),
          )
          as _i4.Future<
            _i5.Result<_i3.RegistrationSessionResponse, _i2.Failure>
          >);

  @override
  _i4.Future<_i5.Result<_i3.RegistrationSessionResponse, _i2.Failure>>
  getRegistrationSession(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#getRegistrationSession, [sessionId]),
            returnValue:
                _i4.Future<
                  _i5.Result<_i3.RegistrationSessionResponse, _i2.Failure>
                >.value(
                  _i6.dummyValue<
                    _i5.Result<_i3.RegistrationSessionResponse, _i2.Failure>
                  >(
                    this,
                    Invocation.method(#getRegistrationSession, [sessionId]),
                  ),
                ),
          )
          as _i4.Future<
            _i5.Result<_i3.RegistrationSessionResponse, _i2.Failure>
          >);

  @override
  _i4.Future<_i5.Result<_i3.RegistrationSessionResponse, _i2.Failure>>
  requestSmsVerificationCode(String? sessionId, {String? transport = 'SMS'}) =>
      (super.noSuchMethod(
            Invocation.method(
              #requestSmsVerificationCode,
              [sessionId],
              {#transport: transport},
            ),
            returnValue:
                _i4.Future<
                  _i5.Result<_i3.RegistrationSessionResponse, _i2.Failure>
                >.value(
                  _i6.dummyValue<
                    _i5.Result<_i3.RegistrationSessionResponse, _i2.Failure>
                  >(
                    this,
                    Invocation.method(
                      #requestSmsVerificationCode,
                      [sessionId],
                      {#transport: transport},
                    ),
                  ),
                ),
          )
          as _i4.Future<
            _i5.Result<_i3.RegistrationSessionResponse, _i2.Failure>
          >);

  @override
  _i4.Future<_i5.Result<_i3.RegistrationSessionResponse, _i2.Failure>>
  verifyAccount(
    String? sessionId,
    String? code, {
    String? deviceId,
    String? deviceName,
    String? platform,
    String? clientVersion,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #verifyAccount,
              [sessionId, code],
              {
                #deviceId: deviceId,
                #deviceName: deviceName,
                #platform: platform,
                #clientVersion: clientVersion,
              },
            ),
            returnValue:
                _i4.Future<
                  _i5.Result<_i3.RegistrationSessionResponse, _i2.Failure>
                >.value(
                  _i6.dummyValue<
                    _i5.Result<_i3.RegistrationSessionResponse, _i2.Failure>
                  >(
                    this,
                    Invocation.method(
                      #verifyAccount,
                      [sessionId, code],
                      {
                        #deviceId: deviceId,
                        #deviceName: deviceName,
                        #platform: platform,
                        #clientVersion: clientVersion,
                      },
                    ),
                  ),
                ),
          )
          as _i4.Future<
            _i5.Result<_i3.RegistrationSessionResponse, _i2.Failure>
          >);

  @override
  _i4.Future<_i5.Result<_i3.CreateAccountResponse, _i2.Failure>>
  registerAccount({
    required String? sessionId,
    required String? password,
    required String? deviceName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registerAccount, [], {
              #sessionId: sessionId,
              #password: password,
              #deviceName: deviceName,
            }),
            returnValue:
                _i4.Future<
                  _i5.Result<_i3.CreateAccountResponse, _i2.Failure>
                >.value(
                  _i6.dummyValue<
                    _i5.Result<_i3.CreateAccountResponse, _i2.Failure>
                  >(
                    this,
                    Invocation.method(#registerAccount, [], {
                      #sessionId: sessionId,
                      #password: password,
                      #deviceName: deviceName,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<_i3.CreateAccountResponse, _i2.Failure>>);
}

/// A class which mocks [SigmaStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockSigmaStore extends _i1.Mock implements _i2.SigmaStore {
  MockSigmaStore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AccountStore get account =>
      (super.noSuchMethod(
            Invocation.getter(#account),
            returnValue: _FakeAccountStore_0(this, Invocation.getter(#account)),
          )
          as _i2.AccountStore);

  @override
  _i2.KeyStore get keys =>
      (super.noSuchMethod(
            Invocation.getter(#keys),
            returnValue: _FakeKeyStore_1(this, Invocation.getter(#keys)),
          )
          as _i2.KeyStore);

  @override
  _i2.SettingsStore get settings =>
      (super.noSuchMethod(
            Invocation.getter(#settings),
            returnValue: _FakeSettingsStore_2(
              this,
              Invocation.getter(#settings),
            ),
          )
          as _i2.SettingsStore);

  @override
  _i4.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [KeysService].
///
/// See the documentation for Mockito's code generation for more information.
class MockKeysService extends _i1.Mock implements _i2.KeysService {
  MockKeysService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.GeneratedKey> generateIdentityKeyPair() =>
      (super.noSuchMethod(
            Invocation.method(#generateIdentityKeyPair, []),
            returnValue: _i4.Future<_i2.GeneratedKey>.value(
              _FakeGeneratedKey_3(
                this,
                Invocation.method(#generateIdentityKeyPair, []),
              ),
            ),
          )
          as _i4.Future<_i2.GeneratedKey>);

  @override
  _i4.Future<_i2.GeneratedKey> generatePreKeyPair(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#generatePreKeyPair, [id]),
            returnValue: _i4.Future<_i2.GeneratedKey>.value(
              _FakeGeneratedKey_3(
                this,
                Invocation.method(#generatePreKeyPair, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.GeneratedKey>);

  @override
  _i4.Future<_i2.GeneratedSignedKey> generateSignedPreKeyPair(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#generateSignedPreKeyPair, [id]),
            returnValue: _i4.Future<_i2.GeneratedSignedKey>.value(
              _FakeGeneratedSignedKey_4(
                this,
                Invocation.method(#generateSignedPreKeyPair, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.GeneratedSignedKey>);

  @override
  _i4.Future<void> generateAndStoreKeys() =>
      (super.noSuchMethod(
            Invocation.method(#generateAndStoreKeys, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getOneTimePreKeysPublic() =>
      (super.noSuchMethod(
            Invocation.method(#getOneTimePreKeysPublic, []),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<String?> getIdentityKey() =>
      (super.noSuchMethod(
            Invocation.method(#getIdentityKey, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<Map<String, dynamic>?> getSignedPreKeyStructured() =>
      (super.noSuchMethod(
            Invocation.method(#getSignedPreKeyStructured, []),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<int?> getRegistrationId() =>
      (super.noSuchMethod(
            Invocation.method(#getRegistrationId, []),
            returnValue: _i4.Future<int?>.value(),
          )
          as _i4.Future<int?>);

  @override
  _i4.Future<List<Map<String, dynamic>>> rotatePreKeys() =>
      (super.noSuchMethod(
            Invocation.method(#rotatePreKeys, []),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [KeyStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockKeyStore extends _i1.Mock implements _i2.KeyStore {
  MockKeyStore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get identityKeyPairKey =>
      (super.noSuchMethod(
            Invocation.getter(#identityKeyPairKey),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#identityKeyPairKey),
            ),
          )
          as String);

  @override
  String get registrationIdKey =>
      (super.noSuchMethod(
            Invocation.getter(#registrationIdKey),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#registrationIdKey),
            ),
          )
          as String);

  @override
  String get signedPreKeyKey =>
      (super.noSuchMethod(
            Invocation.getter(#signedPreKeyKey),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#signedPreKeyKey),
            ),
          )
          as String);

  @override
  String get publicPreKeysKey =>
      (super.noSuchMethod(
            Invocation.getter(#publicPreKeysKey),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#publicPreKeysKey),
            ),
          )
          as String);

  @override
  _i4.Future<void> write(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#write, [key, value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> read(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#read, [key]),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String> getDatabasePassword() =>
      (super.noSuchMethod(
            Invocation.method(#getDatabasePassword, []),
            returnValue: _i4.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#getDatabasePassword, []),
              ),
            ),
          )
          as _i4.Future<String>);
}
