// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: envelope.proto

package sigmapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Envelope_Type int32

const (
	Envelope_TYPE_UNKNOWN  Envelope_Type = 0
	Envelope_CIPHERTEXT    Envelope_Type = 1
	Envelope_PREKEY_BUNDLE Envelope_Type = 2
	Envelope_RECEIPT       Envelope_Type = 3
)

// Enum value maps for Envelope_Type.
var (
	Envelope_Type_name = map[int32]string{
		0: "TYPE_UNKNOWN",
		1: "CIPHERTEXT",
		2: "PREKEY_BUNDLE",
		3: "RECEIPT",
	}
	Envelope_Type_value = map[string]int32{
		"TYPE_UNKNOWN":  0,
		"CIPHERTEXT":    1,
		"PREKEY_BUNDLE": 2,
		"RECEIPT":       3,
	}
)

func (x Envelope_Type) Enum() *Envelope_Type {
	p := new(Envelope_Type)
	*p = x
	return p
}

func (x Envelope_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Envelope_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_envelope_proto_enumTypes[0].Descriptor()
}

func (Envelope_Type) Type() protoreflect.EnumType {
	return &file_envelope_proto_enumTypes[0]
}

func (x Envelope_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Envelope_Type.Descriptor instead.
func (Envelope_Type) EnumDescriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{0, 0}
}

type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          Envelope_Type          `protobuf:"varint,1,opt,name=type,proto3,enum=sigmapb.Envelope_Type" json:"type,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	SourceDevice  uint32                 `protobuf:"varint,3,opt,name=source_device,json=sourceDevice,proto3" json:"source_device,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Content       []byte                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetType() Envelope_Type {
	if x != nil {
		return x.Type
	}
	return Envelope_TYPE_UNKNOWN
}

func (x *Envelope) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Envelope) GetSourceDevice() uint32 {
	if x != nil {
		return x.SourceDevice
	}
	return 0
}

func (x *Envelope) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Envelope) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_envelope_proto protoreflect.FileDescriptor

const file_envelope_proto_rawDesc = "" +
	"\n" +
	"\x0eenvelope.proto\x12\asigmapb\"\xf5\x01\n" +
	"\bEnvelope\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.sigmapb.Envelope.TypeR\x04type\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12#\n" +
	"\rsource_device\x18\x03 \x01(\rR\fsourceDevice\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x04R\ttimestamp\x12\x18\n" +
	"\acontent\x18\x05 \x01(\fR\acontent\"H\n" +
	"\x04Type\x12\x10\n" +
	"\fTYPE_UNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"CIPHERTEXT\x10\x01\x12\x11\n" +
	"\rPREKEY_BUNDLE\x10\x02\x12\v\n" +
	"\aRECEIPT\x10\x03B\x1cZ\x1asigma-server/proto;sigmapbb\x06proto3"

var (
	file_envelope_proto_rawDescOnce sync.Once
	file_envelope_proto_rawDescData []byte
)

func file_envelope_proto_rawDescGZIP() []byte {
	file_envelope_proto_rawDescOnce.Do(func() {
		file_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_envelope_proto_rawDesc), len(file_envelope_proto_rawDesc)))
	})
	return file_envelope_proto_rawDescData
}

var file_envelope_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_envelope_proto_goTypes = []any{
	(Envelope_Type)(0), // 0: sigmapb.Envelope.Type
	(*Envelope)(nil),   // 1: sigmapb.Envelope
}
var file_envelope_proto_depIdxs = []int32{
	0, // 0: sigmapb.Envelope.type:type_name -> sigmapb.Envelope.Type
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_envelope_proto_init() }
func file_envelope_proto_init() {
	if File_envelope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_envelope_proto_rawDesc), len(file_envelope_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_envelope_proto_goTypes,
		DependencyIndexes: file_envelope_proto_depIdxs,
		EnumInfos:         file_envelope_proto_enumTypes,
		MessageInfos:      file_envelope_proto_msgTypes,
	}.Build()
	File_envelope_proto = out.File
	file_envelope_proto_goTypes = nil
	file_envelope_proto_depIdxs = nil
}
