// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: keys.proto

package sigmapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PreKeyRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreKeyRecord) Reset() {
	*x = PreKeyRecord{}
	mi := &file_keys_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreKeyRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreKeyRecord) ProtoMessage() {}

func (x *PreKeyRecord) ProtoReflect() protoreflect.Message {
	mi := &file_keys_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreKeyRecord.ProtoReflect.Descriptor instead.
func (*PreKeyRecord) Descriptor() ([]byte, []int) {
	return file_keys_proto_rawDescGZIP(), []int{0}
}

func (x *PreKeyRecord) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PreKeyRecord) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type PreKeyBundle struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	IdentityKey           []byte                 `protobuf:"bytes,1,opt,name=identity_key,json=identityKey,proto3" json:"identity_key,omitempty"`
	RegistrationId        uint32                 `protobuf:"varint,2,opt,name=registration_id,json=registrationId,proto3" json:"registration_id,omitempty"`
	SignedPreKeyId        int32                  `protobuf:"varint,3,opt,name=signed_pre_key_id,json=signedPreKeyId,proto3" json:"signed_pre_key_id,omitempty"`
	SignedPreKeyPublic    []byte                 `protobuf:"bytes,4,opt,name=signed_pre_key_public,json=signedPreKeyPublic,proto3" json:"signed_pre_key_public,omitempty"`
	SignedPreKeySignature []byte                 `protobuf:"bytes,5,opt,name=signed_pre_key_signature,json=signedPreKeySignature,proto3" json:"signed_pre_key_signature,omitempty"`
	PreKeys               []*PreKeyRecord        `protobuf:"bytes,6,rep,name=pre_keys,json=preKeys,proto3" json:"pre_keys,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PreKeyBundle) Reset() {
	*x = PreKeyBundle{}
	mi := &file_keys_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreKeyBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreKeyBundle) ProtoMessage() {}

func (x *PreKeyBundle) ProtoReflect() protoreflect.Message {
	mi := &file_keys_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreKeyBundle.ProtoReflect.Descriptor instead.
func (*PreKeyBundle) Descriptor() ([]byte, []int) {
	return file_keys_proto_rawDescGZIP(), []int{1}
}

func (x *PreKeyBundle) GetIdentityKey() []byte {
	if x != nil {
		return x.IdentityKey
	}
	return nil
}

func (x *PreKeyBundle) GetRegistrationId() uint32 {
	if x != nil {
		return x.RegistrationId
	}
	return 0
}

func (x *PreKeyBundle) GetSignedPreKeyId() int32 {
	if x != nil {
		return x.SignedPreKeyId
	}
	return 0
}

func (x *PreKeyBundle) GetSignedPreKeyPublic() []byte {
	if x != nil {
		return x.SignedPreKeyPublic
	}
	return nil
}

func (x *PreKeyBundle) GetSignedPreKeySignature() []byte {
	if x != nil {
		return x.SignedPreKeySignature
	}
	return nil
}

func (x *PreKeyBundle) GetPreKeys() []*PreKeyRecord {
	if x != nil {
		return x.PreKeys
	}
	return nil
}

var File_keys_proto protoreflect.FileDescriptor

const file_keys_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"keys.proto\x12\asigmapb\"=\n" +
	"\fPreKeyRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\"\xa3\x02\n" +
	"\fPreKeyBundle\x12!\n" +
	"\fidentity_key\x18\x01 \x01(\fR\videntityKey\x12'\n" +
	"\x0fregistration_id\x18\x02 \x01(\rR\x0eregistrationId\x12)\n" +
	"\x11signed_pre_key_id\x18\x03 \x01(\x05R\x0esignedPreKeyId\x121\n" +
	"\x15signed_pre_key_public\x18\x04 \x01(\fR\x12signedPreKeyPublic\x127\n" +
	"\x18signed_pre_key_signature\x18\x05 \x01(\fR\x15signedPreKeySignature\x120\n" +
	"\bpre_keys\x18\x06 \x03(\v2\x15.sigmapb.PreKeyRecordR\apreKeysB\x1cZ\x1asigma-server/proto;sigmapbb\x06proto3"

var (
	file_keys_proto_rawDescOnce sync.Once
	file_keys_proto_rawDescData []byte
)

func file_keys_proto_rawDescGZIP() []byte {
	file_keys_proto_rawDescOnce.Do(func() {
		file_keys_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_keys_proto_rawDesc), len(file_keys_proto_rawDesc)))
	})
	return file_keys_proto_rawDescData
}

var file_keys_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_keys_proto_goTypes = []any{
	(*PreKeyRecord)(nil), // 0: sigmapb.PreKeyRecord
	(*PreKeyBundle)(nil), // 1: sigmapb.PreKeyBundle
}
var file_keys_proto_depIdxs = []int32{
	0, // 0: sigmapb.PreKeyBundle.pre_keys:type_name -> sigmapb.PreKeyRecord
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_keys_proto_init() }
func file_keys_proto_init() {
	if File_keys_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_keys_proto_rawDesc), len(file_keys_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_keys_proto_goTypes,
		DependencyIndexes: file_keys_proto_depIdxs,
		MessageInfos:      file_keys_proto_msgTypes,
	}.Build()
	File_keys_proto = out.File
	file_keys_proto_goTypes = nil
	file_keys_proto_depIdxs = nil
}
