// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: ui/sigma/proto/message.proto

package sigmapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Envelope_Type int32

const (
	Envelope_TYPE_UNKNOWN      Envelope_Type = 0
	Envelope_CIPHERTEXT        Envelope_Type = 1
	Envelope_PREKEY_BUNDLE     Envelope_Type = 2
	Envelope_PLAINTEXT_CONTENT Envelope_Type = 3
)

// Enum value maps for Envelope_Type.
var (
	Envelope_Type_name = map[int32]string{
		0: "TYPE_UNKNOWN",
		1: "CIPHERTEXT",
		2: "PREKEY_BUNDLE",
		3: "PLAINTEXT_CONTENT",
	}
	Envelope_Type_value = map[string]int32{
		"TYPE_UNKNOWN":      0,
		"CIPHERTEXT":        1,
		"PREKEY_BUNDLE":     2,
		"PLAINTEXT_CONTENT": 3,
	}
)

func (x Envelope_Type) Enum() *Envelope_Type {
	p := new(Envelope_Type)
	*p = x
	return p
}

func (x Envelope_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Envelope_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_ui_sigma_proto_message_proto_enumTypes[0].Descriptor()
}

func (Envelope_Type) Type() protoreflect.EnumType {
	return &file_ui_sigma_proto_message_proto_enumTypes[0]
}

func (x Envelope_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Envelope_Type.Descriptor instead.
func (Envelope_Type) EnumDescriptor() ([]byte, []int) {
	return file_ui_sigma_proto_message_proto_rawDescGZIP(), []int{0, 0}
}

type Envelope struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Type                 Envelope_Type          `protobuf:"varint,1,opt,name=type,proto3,enum=sigmapb.Envelope_Type" json:"type,omitempty"`
	ServerGuid           string                 `protobuf:"bytes,2,opt,name=server_guid,json=serverGuid,proto3" json:"server_guid,omitempty"`
	SourceServiceId      string                 `protobuf:"bytes,3,opt,name=source_service_id,json=sourceServiceId,proto3" json:"source_service_id,omitempty"`
	DestinationServiceId string                 `protobuf:"bytes,4,opt,name=destination_service_id,json=destinationServiceId,proto3" json:"destination_service_id,omitempty"`
	ClientTimestamp      int64                  `protobuf:"varint,5,opt,name=client_timestamp,json=clientTimestamp,proto3" json:"client_timestamp,omitempty"`
	ServerTimestamp      int64                  `protobuf:"varint,6,opt,name=server_timestamp,json=serverTimestamp,proto3" json:"server_timestamp,omitempty"`
	Content              []byte                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	Ephemeral            bool                   `protobuf:"varint,8,opt,name=ephemeral,proto3" json:"ephemeral,omitempty"`
	Urgent               bool                   `protobuf:"varint,9,opt,name=urgent,proto3" json:"urgent,omitempty"`
	Story                bool                   `protobuf:"varint,10,opt,name=story,proto3" json:"story,omitempty"`
	ReportSpamToken      []byte                 `protobuf:"bytes,11,opt,name=report_spam_token,json=reportSpamToken,proto3" json:"report_spam_token,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_ui_sigma_proto_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_ui_sigma_proto_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_ui_sigma_proto_message_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetType() Envelope_Type {
	if x != nil {
		return x.Type
	}
	return Envelope_TYPE_UNKNOWN
}

func (x *Envelope) GetServerGuid() string {
	if x != nil {
		return x.ServerGuid
	}
	return ""
}

func (x *Envelope) GetSourceServiceId() string {
	if x != nil {
		return x.SourceServiceId
	}
	return ""
}

func (x *Envelope) GetDestinationServiceId() string {
	if x != nil {
		return x.DestinationServiceId
	}
	return ""
}

func (x *Envelope) GetClientTimestamp() int64 {
	if x != nil {
		return x.ClientTimestamp
	}
	return 0
}

func (x *Envelope) GetServerTimestamp() int64 {
	if x != nil {
		return x.ServerTimestamp
	}
	return 0
}

func (x *Envelope) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Envelope) GetEphemeral() bool {
	if x != nil {
		return x.Ephemeral
	}
	return false
}

func (x *Envelope) GetUrgent() bool {
	if x != nil {
		return x.Urgent
	}
	return false
}

func (x *Envelope) GetStory() bool {
	if x != nil {
		return x.Story
	}
	return false
}

func (x *Envelope) GetReportSpamToken() []byte {
	if x != nil {
		return x.ReportSpamToken
	}
	return nil
}

var File_ui_sigma_proto_message_proto protoreflect.FileDescriptor

const file_ui_sigma_proto_message_proto_rawDesc = "" +
	"\n" +
	"\x1cui/sigma/proto/message.proto\x12\asigmapb\"\xf5\x03\n" +
	"\bEnvelope\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.sigmapb.Envelope.TypeR\x04type\x12\x1f\n" +
	"\vserver_guid\x18\x02 \x01(\tR\n" +
	"serverGuid\x12*\n" +
	"\x11source_service_id\x18\x03 \x01(\tR\x0fsourceServiceId\x124\n" +
	"\x16destination_service_id\x18\x04 \x01(\tR\x14destinationServiceId\x12)\n" +
	"\x10client_timestamp\x18\x05 \x01(\x03R\x0fclientTimestamp\x12)\n" +
	"\x10server_timestamp\x18\x06 \x01(\x03R\x0fserverTimestamp\x12\x18\n" +
	"\acontent\x18\a \x01(\fR\acontent\x12\x1c\n" +
	"\tephemeral\x18\b \x01(\bR\tephemeral\x12\x16\n" +
	"\x06urgent\x18\t \x01(\bR\x06urgent\x12\x14\n" +
	"\x05story\x18\n" +
	" \x01(\bR\x05story\x12*\n" +
	"\x11report_spam_token\x18\v \x01(\fR\x0freportSpamToken\"R\n" +
	"\x04Type\x12\x10\n" +
	"\fTYPE_UNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"CIPHERTEXT\x10\x01\x12\x11\n" +
	"\rPREKEY_BUNDLE\x10\x02\x12\x15\n" +
	"\x11PLAINTEXT_CONTENT\x10\x03B%Z#sigma-server/ui/sigma/proto;sigmapbb\x06proto3"

var (
	file_ui_sigma_proto_message_proto_rawDescOnce sync.Once
	file_ui_sigma_proto_message_proto_rawDescData []byte
)

func file_ui_sigma_proto_message_proto_rawDescGZIP() []byte {
	file_ui_sigma_proto_message_proto_rawDescOnce.Do(func() {
		file_ui_sigma_proto_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ui_sigma_proto_message_proto_rawDesc), len(file_ui_sigma_proto_message_proto_rawDesc)))
	})
	return file_ui_sigma_proto_message_proto_rawDescData
}

var file_ui_sigma_proto_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ui_sigma_proto_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ui_sigma_proto_message_proto_goTypes = []any{
	(Envelope_Type)(0), // 0: sigmapb.Envelope.Type
	(*Envelope)(nil),   // 1: sigmapb.Envelope
}
var file_ui_sigma_proto_message_proto_depIdxs = []int32{
	0, // 0: sigmapb.Envelope.type:type_name -> sigmapb.Envelope.Type
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ui_sigma_proto_message_proto_init() }
func file_ui_sigma_proto_message_proto_init() {
	if File_ui_sigma_proto_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ui_sigma_proto_message_proto_rawDesc), len(file_ui_sigma_proto_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ui_sigma_proto_message_proto_goTypes,
		DependencyIndexes: file_ui_sigma_proto_message_proto_depIdxs,
		EnumInfos:         file_ui_sigma_proto_message_proto_enumTypes,
		MessageInfos:      file_ui_sigma_proto_message_proto_msgTypes,
	}.Build()
	File_ui_sigma_proto_message_proto = out.File
	file_ui_sigma_proto_message_proto_goTypes = nil
	file_ui_sigma_proto_message_proto_depIdxs = nil
}
