// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/websocket.proto

package sigmapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WebSocketMessage_Type int32

const (
	WebSocketMessage_TYPE_UNKNOWN WebSocketMessage_Type = 0
	WebSocketMessage_REQUEST      WebSocketMessage_Type = 1
	WebSocketMessage_RESPONSE     WebSocketMessage_Type = 2
	WebSocketMessage_MESSAGE      WebSocketMessage_Type = 3
)

// Enum value maps for WebSocketMessage_Type.
var (
	WebSocketMessage_Type_name = map[int32]string{
		0: "TYPE_UNKNOWN",
		1: "REQUEST",
		2: "RESPONSE",
		3: "MESSAGE",
	}
	WebSocketMessage_Type_value = map[string]int32{
		"TYPE_UNKNOWN": 0,
		"REQUEST":      1,
		"RESPONSE":     2,
		"MESSAGE":      3,
	}
)

func (x WebSocketMessage_Type) Enum() *WebSocketMessage_Type {
	p := new(WebSocketMessage_Type)
	*p = x
	return p
}

func (x WebSocketMessage_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WebSocketMessage_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_websocket_proto_enumTypes[0].Descriptor()
}

func (WebSocketMessage_Type) Type() protoreflect.EnumType {
	return &file_proto_websocket_proto_enumTypes[0]
}

func (x WebSocketMessage_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WebSocketMessage_Type.Descriptor instead.
func (WebSocketMessage_Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_websocket_proto_rawDescGZIP(), []int{0, 0}
}

type WebSocketMessage struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Type          WebSocketMessage_Type     `protobuf:"varint,1,opt,name=type,proto3,enum=sigmapb.WebSocketMessage_Type" json:"type,omitempty"`
	Request       *WebSocketRequestMessage  `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	Response      *WebSocketResponseMessage `protobuf:"bytes,3,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketMessage) Reset() {
	*x = WebSocketMessage{}
	mi := &file_proto_websocket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketMessage) ProtoMessage() {}

func (x *WebSocketMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_websocket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketMessage.ProtoReflect.Descriptor instead.
func (*WebSocketMessage) Descriptor() ([]byte, []int) {
	return file_proto_websocket_proto_rawDescGZIP(), []int{0}
}

func (x *WebSocketMessage) GetType() WebSocketMessage_Type {
	if x != nil {
		return x.Type
	}
	return WebSocketMessage_TYPE_UNKNOWN
}

func (x *WebSocketMessage) GetRequest() *WebSocketRequestMessage {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *WebSocketMessage) GetResponse() *WebSocketResponseMessage {
	if x != nil {
		return x.Response
	}
	return nil
}

type WebSocketRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Verb          string                 `protobuf:"bytes,2,opt,name=verb,proto3" json:"verb,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketRequestMessage) Reset() {
	*x = WebSocketRequestMessage{}
	mi := &file_proto_websocket_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketRequestMessage) ProtoMessage() {}

func (x *WebSocketRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_websocket_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketRequestMessage.ProtoReflect.Descriptor instead.
func (*WebSocketRequestMessage) Descriptor() ([]byte, []int) {
	return file_proto_websocket_proto_rawDescGZIP(), []int{1}
}

func (x *WebSocketRequestMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WebSocketRequestMessage) GetVerb() string {
	if x != nil {
		return x.Verb
	}
	return ""
}

func (x *WebSocketRequestMessage) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WebSocketRequestMessage) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type DeleteMessageRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PendingMessageId uint32                 `protobuf:"varint,1,opt,name=pending_message_id,json=pendingMessageId,proto3" json:"pending_message_id,omitempty"`
	MessageId        string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeleteMessageRequest) Reset() {
	*x = DeleteMessageRequest{}
	mi := &file_proto_websocket_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageRequest) ProtoMessage() {}

func (x *DeleteMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_websocket_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageRequest.ProtoReflect.Descriptor instead.
func (*DeleteMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_websocket_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteMessageRequest) GetPendingMessageId() uint32 {
	if x != nil {
		return x.PendingMessageId
	}
	return 0
}

func (x *DeleteMessageRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type WebSocketResponseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketResponseMessage) Reset() {
	*x = WebSocketResponseMessage{}
	mi := &file_proto_websocket_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketResponseMessage) ProtoMessage() {}

func (x *WebSocketResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_websocket_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketResponseMessage.ProtoReflect.Descriptor instead.
func (*WebSocketResponseMessage) Descriptor() ([]byte, []int) {
	return file_proto_websocket_proto_rawDescGZIP(), []int{3}
}

func (x *WebSocketResponseMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WebSocketResponseMessage) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *WebSocketResponseMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WebSocketResponseMessage) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type WebSocketError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketError) Reset() {
	*x = WebSocketError{}
	mi := &file_proto_websocket_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketError) ProtoMessage() {}

func (x *WebSocketError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_websocket_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketError.ProtoReflect.Descriptor instead.
func (*WebSocketError) Descriptor() ([]byte, []int) {
	return file_proto_websocket_proto_rawDescGZIP(), []int{4}
}

func (x *WebSocketError) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_websocket_proto protoreflect.FileDescriptor

const file_proto_websocket_proto_rawDesc = "" +
	"\n" +
	"\x15proto/websocket.proto\x12\asigmapb\"\x83\x02\n" +
	"\x10WebSocketMessage\x122\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1e.sigmapb.WebSocketMessage.TypeR\x04type\x12:\n" +
	"\arequest\x18\x02 \x01(\v2 .sigmapb.WebSocketRequestMessageR\arequest\x12=\n" +
	"\bresponse\x18\x03 \x01(\v2!.sigmapb.WebSocketResponseMessageR\bresponse\"@\n" +
	"\x04Type\x12\x10\n" +
	"\fTYPE_UNKNOWN\x10\x00\x12\v\n" +
	"\aREQUEST\x10\x01\x12\f\n" +
	"\bRESPONSE\x10\x02\x12\v\n" +
	"\aMESSAGE\x10\x03\"e\n" +
	"\x17WebSocketRequestMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04verb\x18\x02 \x01(\tR\x04verb\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\"c\n" +
	"\x14DeleteMessageRequest\x12,\n" +
	"\x12pending_message_id\x18\x01 \x01(\rR\x10pendingMessageId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\"p\n" +
	"\x18WebSocketResponseMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\"&\n" +
	"\x0eWebSocketError\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05errorB\x1cZ\x1asigma-server/proto;sigmapbb\x06proto3"

var (
	file_proto_websocket_proto_rawDescOnce sync.Once
	file_proto_websocket_proto_rawDescData []byte
)

func file_proto_websocket_proto_rawDescGZIP() []byte {
	file_proto_websocket_proto_rawDescOnce.Do(func() {
		file_proto_websocket_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_websocket_proto_rawDesc), len(file_proto_websocket_proto_rawDesc)))
	})
	return file_proto_websocket_proto_rawDescData
}

var file_proto_websocket_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_websocket_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_websocket_proto_goTypes = []any{
	(WebSocketMessage_Type)(0),       // 0: sigmapb.WebSocketMessage.Type
	(*WebSocketMessage)(nil),         // 1: sigmapb.WebSocketMessage
	(*WebSocketRequestMessage)(nil),  // 2: sigmapb.WebSocketRequestMessage
	(*DeleteMessageRequest)(nil),     // 3: sigmapb.DeleteMessageRequest
	(*WebSocketResponseMessage)(nil), // 4: sigmapb.WebSocketResponseMessage
	(*WebSocketError)(nil),           // 5: sigmapb.WebSocketError
}
var file_proto_websocket_proto_depIdxs = []int32{
	0, // 0: sigmapb.WebSocketMessage.type:type_name -> sigmapb.WebSocketMessage.Type
	2, // 1: sigmapb.WebSocketMessage.request:type_name -> sigmapb.WebSocketRequestMessage
	4, // 2: sigmapb.WebSocketMessage.response:type_name -> sigmapb.WebSocketResponseMessage
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_websocket_proto_init() }
func file_proto_websocket_proto_init() {
	if File_proto_websocket_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_websocket_proto_rawDesc), len(file_proto_websocket_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_websocket_proto_goTypes,
		DependencyIndexes: file_proto_websocket_proto_depIdxs,
		EnumInfos:         file_proto_websocket_proto_enumTypes,
		MessageInfos:      file_proto_websocket_proto_msgTypes,
	}.Build()
	File_proto_websocket_proto = out.File
	file_proto_websocket_proto_goTypes = nil
	file_proto_websocket_proto_depIdxs = nil
}
